inherit_from: .rubocop_todo.yml

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  StyleGuide: '#short-methods'
  Enabled: false
  VersionAdded: '0.25'
  VersionChanged: '1.5'
  CountComments: false  # count full line comments?
  Max: 10
  CountAsOne: []
  IgnoredMethods: []
